######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 19:30:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    Dot.cpp \
    Walls.cpp \
    Position.cpp \
    gameLoop.cpp

HEADERS += \
    Dot.h \
    Walls.h \
    Position.h \
    gameLoop.h
