######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 19:30:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    Dot.cpp \
    gameWindow.cpp \
    Walls.cpp

HEADERS += \
    Dot.h \
    gameWindow.h \
    Walls.h
